server:
  port: 8010
spring:
  application:
    name: sys-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true

#ribbon:
#  eureka:
#    enabled: true
