server:
  port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config
  application:
    name: config-server
  profiles:
    active: native  # 配置使用本地储存